[config]

[checks.Environment]
desc = "Check environment variables common to all development environments"

    [checks.Environment.Path]
    desc = "Paths to search for executables"
    checkEnv = "PATH"

    [checks.Environment.Username]
    desc = "The current username"
    checkEnv = "USER"
    regex = "[a-z_][a-z0-9_-]*[$]?"
