[tool.geomancy.config.Check]
env_substitute_default=true

[tool.geomancy.checks.Environment]
desc = "Check environment variables common to all development environments"

    [tool.geomancy.checks.Environment.Path]
    desc = "Paths to search for executables"
    checkEnv = "$PATH"

